api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Productivity/Interfaces/Rest/ApiPlatform/config/resources'
  formats:
    jsonapi:  ['application/vnd.api+json']
    jsonhal:  ['application/hal+json']
    json:     ['application/json']
  #    jsonld:   ['application/ld+json']
#    xml:      ['application/xml', 'text/xml']
#    yaml:     ['application/x-yaml']
#    csv:      ['text/csv']
#    html:     ['text/html']
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [ 3 ]
  enable_swagger_ui: false
  enable_re_doc: false
