doctrine:
  dbal:
    default_connection: projects_projection
    connections:
      event_store:
        url: '%env(resolve:EVENT_STORE_DATABASE_URL)%'
      registered_users_projection:
        url: '%env(resolve:REGISTERED_USERS_PROJECTIONS_DATABASE_URL)%'
        platform_service: Shared\Infrastructure\Doctrine\DBAL\Platforms\PostgreSqlPlatform
      projects_projection:
        url: '%env(resolve:PROJECTS_PROJECTIONS_DATABASE_URL)%'
        platform_service: Shared\Infrastructure\Doctrine\DBAL\Platforms\MySQLPlatform

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
    proxy_namespace: Proxies
    entity_managers:
      event_store:
        connection: event_store
      registered_users_projection:
        connection: registered_users_projection
        mappings:
          custom_mapping:
            type: xml
            prefix: Users\Application\Projector\RegisteredUsers\Doctrine\Entity
            dir: "%kernel.project_dir%/src/Users/Application/Projector/RegisteredUsers/Doctrine/config"
            alias: RegisteredUsers
            is_bundle: false
      projects_projection:
        connection: projects_projection
        mappings:
          custom_mapping:
            type: xml
            prefix: Productivity\Application\Projector\Projects\Doctrine\Entity
            dir: "%kernel.project_dir%/src/Productivity/Application/Projector/Projects/Doctrine/config"
            alias: Projects
            is_bundle: false
