security:
  encoders:
    Users\Application\Projector\RegisteredUsers\Doctrine\Entity\RegisteredUser: 'auto'
  providers:
    registered_users:
      entity:
        class: Users\Application\Projector\RegisteredUsers\Doctrine\Entity\RegisteredUser
        property: username
        manager_name: registered_users_projection
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/api
      stateless: true
      provider: registered_users
      http_basic:
        realm: ToDocler API
    main:
      security: false

  access_control:
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
