version: '3'
services:

  php:
    image: streakphp/php74-cli:latest
    working_dir: /var/www/project
    volumes:
      - .:/var/www/project
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_NO_INTERACTION: 1
    depends_on:
      - postgres_event_store
      - postgres_projections
      - redis

  fpm1:
    image: streakphp/php74-fpm:latest
    working_dir: /var/www/project
    volumes:
      - .:/var/www/project
      - ./docker/fpm/etc/php/7.4/fpm/pool.d/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./docker/fpm/etc/php/7.4/fpm/pool.d/z-overrides.conf:/etc/php/7.4/fpm/pool.d/z-overrides.conf
    depends_on:
      - postgres_event_store
      - postgres_projections
      - redis

  fpm2:
    image: streakphp/php74-fpm:latest
    working_dir: /var/www/project
    volumes:
      - .:/var/www/project
      - ./docker/fpm/etc/php/7.4/fpm/pool.d/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./docker/fpm/etc/php/7.4/fpm/pool.d/z-overrides.conf:/etc/php/7.4/fpm/pool.d/z-overrides.conf
    depends_on:
      - postgres_event_store
      - postgres_projections
      - redis

  nginx:
    image: nginx:alpine
    working_dir: /var/www/project
    volumes:
      - .:/var/www/project
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fpm1
      - fpm2
    ports:
      - 8080:80

  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - ./docker/redis/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  postgres_event_store:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: ${EVENT_STORE_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${EVENT_STORE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${EVENT_STORE_POSTGRES_DATABASE}
    volumes:
      - ./docker/postgres/usr/share/postgresql/9.5/postgresql.conf.sample:/usr/share/postgresql/9.5/postgresql.conf.sample
    ports:
      - 5433:5432

  postgres_projections:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: ${PROJECTIONS_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${PROJECTIONS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROJECTIONS_POSTGRES_DATABASE}
    volumes:
      - ./docker/postgres/usr/share/postgresql/9.5/postgresql.conf.sample:/usr/share/postgresql/9.5/postgresql.conf.sample
    ports:
      - 5434:5432

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgres_event_store
    ports:
      - 8080:8080
