services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Shared\Infrastructure\Doctrine\DBAL\Platforms\PostgreSqlPlatform: ~

  Shared\Infrastructure\Doctrine\DBAL\Platforms\MySQLPlatform: ~
