services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Productivity\Application\Command\ListHandler:
    arguments:
      - '@Streak\Domain\AggregateRoot\Factory'
      - '@Streak\Domain\AggregateRoot\Repository'
