services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Productivity\Infrastructure\Interfaces\Console\Symfony\CreateListCommand:
    arguments:
      - '@Streak\Application\CommandBus'
      - '@Productivity\UsersFacade'
    tags:
      - console.command

  Productivity\Infrastructure\Interfaces\Console\Symfony\CreateTaskCommand:
    arguments:
      - '@Streak\Application\CommandBus'
      - '@Productivity\UsersFacade'
    tags:
      - console.command
