services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Productivity\Application\Projector\Projects\Projector\Factory:
    arguments:
      - '@doctrine.orm.projects_projection_entity_manager'
