services:

  productivity.users_events.sensor.factory:
    class: Productivity\Application\Sensor\UsersEvents\Sensor\Factory

  productivity.users_events.committing.sensor.factory:
    class: Streak\Infrastructure\Application\Sensor\CommittingSensor\Factory
    arguments:
      - '@.inner'
      - '@Streak\Infrastructure\Domain\UnitOfWork'
    decorates: productivity.users_events.sensor.factory

  productivity.users_events.sensor.rabbitmq_consumer:
    class: Streak\Infrastructure\Interfaces\RabbitMQ\SensorConsumer
    arguments:
      - '@productivity.users_events.sensor.factory'

  productivity.users_events.committing.sensor.rabbitmq_consumer:
    class: Streak\Infrastructure\Interfaces\RabbitMQ\CommittingSensorConsumer
    arguments:
      - '@.inner'
      - '@Streak\Infrastructure\Domain\UnitOfWork'
    decorates: productivity.users_events.sensor.rabbitmq_consumer

  Productivity\Application\Sensor\UsersEvents\Sensor\Factory: '@productivity.users_events.sensor.factory'
