services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Users\Domain\User\Factory:
    arguments:
      - '@Users\Domain\PasswordHasher'
      - '@Streak\Domain\Clock'
