services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Users\Application\Command\RegisterUserHandler:
    arguments:
      - '@Streak\Domain\AggregateRoot\Factory'
      - '@Streak\Domain\AggregateRoot\Repository'
