services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Users\Interfaces\Console\Symfony\RegisterUserCommand:
    arguments:
      - '@Streak\Application\CommandBus'
      - '@Streak\Application\QueryBus'
    tags:
      - console.command
