services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Users\Infrastructure\PasswordHasher\SymfonyPasswordHasherAdapter:
    arguments:
      - '@Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface'
      - Users\Application\Projector\RegisteredUsers\Doctrine\Entity\RegisteredUser

  Users\Domain\PasswordHasher: '@Users\Infrastructure\PasswordHasher\SymfonyPasswordHasherAdapter'

  Users\Infrastructure\SaltGenerator\SimpleSaltGenerator:

  Users\Infrastructure\SaltGenerator\FixedSaltGenerator:
    arguments:
      - 'salt'

  Users\Domain\SaltGenerator: '@Users\Infrastructure\SaltGenerator\SimpleSaltGenerator'

  Users\Infrastructure\UsersFacadeForProductivity:
    arguments:
      - '@Streak\Application\QueryBus'

  Users\Infrastructure\Queue\RabbitMQQueue:
    arguments:
      - '@users.integration_events.producer'
      - 'users'
