Productivity\Application\Projector\Lists\Doctrine\Entity\Checklist:
  attributes:
    id:
      groups:
        - 'lists.browse'
        - 'lists.read'
        - 'tasks.browse'
        - 'tasks.read'
        - 'lists.tasks.browse'
    userId:
      ignore: ~
    name:
      groups:
        - 'lists.browse'
        - 'lists.read'
        - 'tasks.browse'
        - 'tasks.read'
        - 'lists.tasks.browse'
    updatedAt:
      groups:
        - 'lists.browse'
        - 'lists.read'
    createdAt:
      groups:
        - 'lists.browse'
        - 'lists.read'
        - 'lists.edit'
    tasks:
      groups:
        - 'lists.browse'
        - 'lists.read'
        - 'lists.edit'
