parameters:
  todocler.first_project.default_name: 'My first project'

imports:
  - { resource: 'services/productivity/*.yaml' }
  - { resource: 'services/users/*.yaml' }
  - { resource: 'services/shared/*.yaml' }
