Productivity\Application\Projector\Lists\Doctrine\Entity\Checklist:
  shortName: 'List'
  attributes:
    order:
      createdAt: desc
      tasks.createdAt: desc
    pagination_items_per_page: 25
    filters:
      - productivity.filters.order_by_created_at
      - productivity.filters.filter_by_created_at
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups: [ 'lists.browse' ]
      openapi_context:
        summary: Retrieves the list of lists
    post:
      method: POST
      status: 202
      messenger: input
      input: Productivity\Infrastructure\Interfaces\Rest\ApiPlatform\DTO\CreateList
      output: false
      read: true
      deserialize: true
      validate: true
      write: true
      serialize: true
      openapi_context:
        summary: Create new list
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups: [ 'lists.read' ]
      openapi_context:
        summary: Retrieves the list
    rename:
      method: PATCH
      status: 202
      messenger: input
      input: Productivity\Infrastructure\Interfaces\Rest\ApiPlatform\DTO\RenameList
      output: false
      read: true
      deserialize: true
      validate: true
      write: true
      serialize: true
      openapi_context:
        summary: Renames the list
    delete:
      method: DELETE
      status: 202
      messenger: input
      # input option is not working with DELETE - api platform sends resource object with delete-stamp instead
      input: Productivity\Infrastructure\Interfaces\Rest\ApiPlatform\DTO\RemoveList
      output: false
      read: true
      deserialize: true
      validate: true
      write: true
      openapi_context:
        summary: Removes the list
