Productivity\Application\Projector\Projects\Doctrine\Entity\Task:
  attributes:
    order:
      createdAt: asc
    pagination_items_per_page: 25
    filters:
      - productivity.filters.order_by_created_at
      - productivity.filters.filter_by_completed
      - productivity.filters.filter_by_created_at
      - productivity.filters.filter_by_project_id
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups: [ 'tasks.browse' ]
      openapi_context:
        summary: Retrieves the list of tasks
    post:
      method: POST
      status: 202
      messenger: input
      input: Productivity\Infrastructure\Interfaces\Rest\ApiPlatform\DTO\CreateTask
      output: false
      read: true
      deserialize: true
      validate: true
      write: true
      serialize: true
      openapi_context:
        summary: Creates new task
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups: [ 'tasks.read' ]
      openapi_context:
        summary: Retrieves the task
    complete:
      method: POST
      path: /tasks/{id}/complete
      controller: api_platform.action.placeholder
      status: 202
      messenger: input
      input: Productivity\Infrastructure\Interfaces\Rest\ApiPlatform\DTO\CompleteTask
      output: false
      read: true
      deserialize: true
      validate: true
      write: true
      serialize: true
      openapi_context:
        summary: Completes the task
    delete:
      method: DELETE
      status: 202
      messenger: input
      # input option is not working with DELETE - api platform sends resource object with delete-stamp instead
      input: Productivity\Infrastructure\Interfaces\Rest\ApiPlatform\DTO\RemoveTask
      output: false
      read: true
      deserialize: true
      validate: true
      write: true
      serialize: true
      openapi_context:
        summary: Removes the task

