Productivity\Application\Projector\Lists\Doctrine\Entity\Checklist:
  collectionOperations:
    get:
      method: get
  itemOperations:
    get:
      method: GET
  properties:
    tasks:
      subresource:
        resourceClass: Productivity\Application\Projector\Lists\Doctrine\Entity\Task
        collection: true
