name: CI
on: [push]
jobs:
  validate-composer:
    name: composer validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run composer validate
        run: docker-compose run --rm --no-deps php composer validate --strict --no-interaction --ansi
  run-php-cs-fixer:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: docker-compose run --rm php composer install --no-interaction --optimize-autoloader --ansi
      - name: Run php-cs-fixer
        run: docker-compose run --rm --no-deps php bin/php-cs-fixer fix --diff --dry-run --ansi
  run-phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: docker-compose run --rm php composer install --no-interaction --optimize-autoloader --ansi
      - name: Run phpunit
        run: docker-compose run --rm php xphp bin/phpunit --color=always
      - name: Check coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "95"
          filename: "var/phpunit/clover.xml"
