name: CI
on: [push]
jobs:
  validate-composer:
    name: composer validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker pull
        run: docker-compose pull php
#      - name: Docker build
#        run: docker-compose build --force-rm
      - name: Run composer validate
        run: docker-compose run --rm --no-deps php composer validate --strict --no-interaction --ansi
  run-php-cs-fixer:
    name: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker pull
        run: docker-compose pull php
#      - name: Docker build
#        run: docker-compose build --force-rm
      - name: Composer caching
        uses: actions/cache@v2
        with:
          path: ./build/.composer
          key: ${{ runner.os }}-composer-v1-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-v1-
      - name: Install dependencies
        run: docker-compose run --rm --no-deps php composer install --no-scripts --no-interaction --optimize-autoloader --ansi
      - name: Run php-cs-fixer
        run: docker-compose run --rm --no-deps php bin/php-cs-fixer fix --diff --dry-run --ansi --config=.php-cs-fixer.dist.php
  run-phpunit:
    name: phpunit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker pull
        run: docker-compose pull
#      - name: Docker build
#        run: docker-compose build --force-rm
      - name: Composer caching
        uses: actions/cache@v2
        with:
          path: ./build/.composer
          key: ${{ runner.os }}-composer-v1-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-v1-
      - name: Install dependencies
        run: docker-compose run --rm php composer install --no-scripts --no-interaction --optimize-autoloader --ansi
      - name: Run phpunit
        run: docker-compose run --rm php xphp -dxdebug.mode=coverage bin/phpunit --color=always --configuration=phpunit.xml.dist
      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: ./build/.phpunit/clover.xml
          fail_ci_if_error: true
          verbose: true
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: PHPUnit Code Coverage
          path: ./build/.phpunit/code-coverage
          retention-days: 7
  run-rector:
    name: rector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker pull
        run: docker-compose pull php
#      - name: Docker build
#        run: docker-compose build --force-rm
      - name: Composer caching
        uses: actions/cache@v2
        with:
          path: ./build/.composer
          key: ${{ runner.os }}-composer-v1-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-v1-
      - name: Install dependencies
        run: docker-compose run --rm --no-deps php composer install --no-interaction --optimize-autoloader --ansi
      - name: Run rector
        run: docker-compose run --rm --no-deps php bin/rector --no-progress-bar --dry-run --ansi
  run-deptrac:
    name: deptrac
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker pull
        run: docker-compose pull php
#      - name: Docker build
#        run: docker-compose build --force-rm
      - name: Composer caching
        uses: actions/cache@v2
        with:
          path: ./build/.composer
          key: ${{ runner.os }}-composer-v1-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-v1-
      - name: Install dependencies
        run: docker-compose run --rm --no-deps php composer install --no-scripts --no-interaction --optimize-autoloader --ansi
      - name: Run deptrac
        run: docker-compose run --rm --no-deps php bin/deptrac --no-progress --no-interaction --cache-file=./build/.deptrac/.deptrac.cache --ansi
